spring:
  datasource:
    url: jdbc:h2:mem:commondb;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS MYSCHEMA\;SET SCHEMA MYSCHEMA
    username: sa
    password:
    driver-class-name: 

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs