INSERT INTO COMMON_USER
    (USERNAME, EMAIL, ACTIVE)
VALUES
    ('admin', 'admin@example.com', TRUE);

INSERT INTO COMMON_USER
    (USERNAME, EMAIL, ACTIVE)
VALUES
    ('testuser', 'test@example.com', TRUE);

INSERT INTO COMMON_AUDIT
    (USER_ID, ACTION)
VALUES
    (1, 'USER_CREATED');

INSERT INTO COMMON_AUDIT
    (USER_ID, ACTION)
VALUES
    (2, 'USER_CREATED');